### ISSUE TITLE
Cannot get past Missing Keys or Out of date you should reinstall

### ISSUE THREAD

**Issue by dbltoe** [lat9/usps#13]
Since not in the downloads yet, I bring this here.

Had problems putting this on an existing 1.5.7 and was not sure if something from the previous installation was the problem.

I have a test site with free shipping and USPS never installed.

Installed and entered USPS Web Tools User ID and made selections for rates normally used by our customers.

It will not let me past the warning and remains with the yellow dot of purgatory.

![usps](https://user-images.githubusercontent.com/5122886/95692821-41438c80-0bee-11eb-87cd-da331fb56cec.png)

**Comment by lat9** [comment]
As you indicated, that's because this version of the shipping-module is not yet in the Zen Cart downloads.  Other than that warning, all 'should' be good.

**Comment by lat9** [comment]
I've updated the tag on that `-beta` release to indicate that it's a pre-release.  Waiting for some feedback that I haven't broken something before I submit to the Zen Cart plugins.

**Comment by dbltoe** [comment]
Until it turns the dot green, I can't test further but there is no real rush.  I have one site that charges too much for one item but I just tell the customer I was able to "get it in a smaller box" and give them a little rebate.  So far, no one's complained.  ;-)

**Comment by lat9** [comment]
The shipping module should still give quotes; that yellow-dot only affects the display in the admin.

**Comment by dbltoe** [comment]
No other shipping but USPS, estimator set to 2, product set to two ounces.
![estimator](https://user-images.githubusercontent.com/5122886/95748115-22311300-0c5f-11eb-8fbd-64348159f8b9.png)

**Comment by lat9** [comment]
Any logs?  What shipping options were selected?

**Comment by dbltoe** [comment]
No Logs even after enabling debug.  Settings in PDF.  I left out the ID but it was there for all tests.
[USPS_Settings.pdf](https://github.com/lat9/usps/files/5365804/USPS_Settings.pdf)

**Comment by lat9** [comment]
Hmm, I'll need to investigate (later); I'm not seeing that locally.

**Comment by lat9** [comment]
Did you put the USPS shipping module into its "Debug Mode" (towards the bottom of the plethora of settings)?

**Comment by dbltoe** [comment]
Apologies on two counts.  Late night is reason for slow response.
PDF was made before debug mode was set to logs.
Testing with set to Logs resulted in no generated logs in /logs

**Comment by lat9** [comment]
Any difference if you disable the 'check for updates' in the shipping-module?
```php
    // -----
    // Class constant to define the shipping-method's Zen Cart plugin ID.
    //
    const USPS_ZEN_CART_PLUGIN_ID = 1292;   //- Set to 0 to disable plugin-version checking.
```

**Comment by dbltoe** [comment]
No difference

**Comment by lat9** [comment]
OK, I give.  Would you send me a direct email with the access information for the test site?

**Comment by lat9** [comment]
It looks like the base issue is that the majority of the products on the test site have the **Always Free Shipping** selection set to **Yes, Always Free Shipping**.

**Comment by dbltoe** [comment]
My bad, I thought I had changed that when I added weight to the item.  The reason it was on that site was that I had the same problem on a live site that has no free shipping.  Same indication as the graphic in my first post.  The live site DOES have several free options installed but all are set to false.
That made me move to the test site for my screw up.  I will try again on one of my live sites that is clean. :blush:

**Comment by dbltoe** [comment]
I'm sorry, I thought you were still working.  Product is regular shipping.  Still get the Missing Keys or Out of Date.

Is it not going to work unless all items are not free shipping.  What %

**Comment by lat9** [comment]
That "Missing Keys or Out of Date" affects _only_ the admin's display.  `USPS` (along with all other shipping modules) backs out of the storefront if `zen_get_shipping_enabled` (present in /includes/functions/functions_general.php) returns `false`:
```php
////
// enable shipping
  function zen_get_shipping_enabled($shipping_module) {
    global $PHP_SELF, $order;

    // for admin always true if installed
    if (strstr($PHP_SELF, FILENAME_MODULES)) {
      return true;
    }

    $check_cart_free = $_SESSION['cart']->in_cart_check('product_is_always_free_shipping','1');
    $check_cart_cnt = $_SESSION['cart']->count_contents();
    $check_cart_weight = $_SESSION['cart']->show_weight();

    switch(true) {
      // for admin always true if installed
      case (strstr($PHP_SELF, FILENAME_MODULES)):
        return true;
        break;
      // Free Shipping when 0 weight - enable freeshipper - ORDER_WEIGHT_ZERO_STATUS must be on
      case (ORDER_WEIGHT_ZERO_STATUS == '1' and ($check_cart_weight == 0 and $shipping_module == 'freeshipper')):
        return true;
        break;
      // Free Shipping when 0 weight - disable everyone - ORDER_WEIGHT_ZERO_STATUS must be on
      case (ORDER_WEIGHT_ZERO_STATUS == '1' and ($check_cart_weight == 0 and $shipping_module != 'freeshipper')):
        return false;
        break;
      case (($_SESSION['cart']->free_shipping_items() == $check_cart_cnt) and $shipping_module == 'freeshipper'):
        return true;
        break;
      case (($_SESSION['cart']->free_shipping_items() == $check_cart_cnt) and $shipping_module != 'freeshipper'):
        return false;
        break;
      // Always free shipping only true - enable freeshipper
      case (($check_cart_free == $check_cart_cnt) and $shipping_module == 'freeshipper'):
        return true;
        break;
      // Always free shipping only true - disable everyone
      case (($check_cart_free == $check_cart_cnt) and $shipping_module != 'freeshipper'):
        return false;
        break;
      // Always free shipping only is false - disable freeshipper
      case (($check_cart_free != $check_cart_cnt) and $shipping_module == 'freeshipper'):
        return false;
        break;
      default:
        return true;
        break;
    }
  }
```

Noting also that the shopping_cart's `free_shipping_items` returns the count of products that match:
```php

        // shipping adjustments for Product
        if (($product->fields['product_is_always_free_shipping'] == 1) or ($product->fields['products_virtual'] == 1) or (preg_match('/^GIFT/', addslashes($product->fields['products_model'])))) {
          $this->free_shipping_item += $qty;
          $freeShippingTotal += $products_price;
          $this->free_shipping_weight += ($qty * $product->fields['products_weight']);
        }
```
... so that's the count of products marked 'always free shipping', those that are virtual and gift-certificates.  I've enabled the `freeshipper` shipping method on your test site so that (at least) the "Free Shipping" will show on your storefront.
