### ISSUE TITLE
commitname coming back as an empty array.

### ISSUE THREAD

**Issue by proseLA** [lat9/usps#23]
i am not sure if the spec has changed or what.  but i am getting an empty array being returned for `$Package['CommitmentName']`.  which means it is set.  so i am then getting a array to string conversion error on the debug line.

now, i am not sure if the package actually returned a commitname, whether it would be in an array or as a string which is what the assumption is here (i have limited experience with this module):
https://github.com/lat9/usps/blob/7887ac0667c5a96c36f0f0f2d0c9f739cf2b5c5a/includes/modules/shipping/usps.php#L1895-L1899

![image](https://user-images.githubusercontent.com/1095136/179428955-571ed359-1501-4e0f-aba9-1069401ae483.png)

**Comment by lat9** [comment]
**_Note-to-self:_**  I've not updated the in-module current version yet, since that will result in complications if/when additional issues are identified.

I'll hold this change for another week to see if anything else creeps in to prevent additional churn.
