### ISSUE TITLE
Cannot access protected property

### ISSUE THREAD

**Issue by dbltoe** [lat9/usps#30]
157d site topkayaker.com and allpecans.com --  okay on sepialiterature.info
Trying to figure what's different

`[30-Jan-2023 11:29:26 America/New_York] PHP Fatal error: Uncaught Error: Cannot access protected property usps::$tax_class in /includes/modules/order_total/ot_shipping.php:81
Stack trace:
#0 /includes/classes/order_total.php(178): ot_shipping->process()
#1 /includes/modules/pages/checkout_one_confirmation/header_php.php(221): order_total->pre_confirmation_check()
#2 /index.php(35): require('/home/topkathe/...')
#3 {main}
thrown in /includes/modules/order_total/ot_shipping.php on line 81

[30-Jan-2023 11:29:26 America/New_York] Request URI: /index.php?main_page=checkout_one_confirmation, IP address: 174.212.97.89
--> PHP Fatal error: Uncaught Error: Cannot access protected property usps::$tax_class in /includes/modules/order_total/ot_shipping.php:81
Stack trace:
#0 /includes/classes/order_total.php(178): ot_shipping->process()
#1 /includes/modules/pages/checkout_one_confirmation/header_php.php(221): order_total->pre_confirmation_check()
#2 /index.php(35): require('/home/topkathe/...')
#3 {main}
thrown in /includes/modules/order_total/ot_shipping.php on line 81.`

**Comment by lat9** [comment]
Dang it.  Update forthcoming.

Thanks for the report.
