### ISSUE TITLE
USPS 'cheapest' quotes aren't selected

### ISSUE THREAD

**Issue by lat9** [lat9/usps#32]
... as identified in [this](https://www.zen-cart.com/showthread.php?227284-USPS-Shipping-Module-Support-Thread&p=1392777#post1392777) Zen Cart support-thread posting.

**Comment by dbltoe** [comment]
should new line 127 be changed to reflect h?

**Comment by dbltoe** [comment]
Tested with both updates and the change to new line 127.

Auto updates from g and reports version h.

**Comment by lat9** [comment]
> should new line 127 be changed to reflect h?

It will be, prior to release.  I didn't want to 'jump the gun' like I did a couple of days ago.
