### ISSUE TITLE
country United States. State: puerto rico, NO quotes at all

### ISSUE THREAD

**Issue by jjone** [lat9/usps#43]
in ESTIMATE SHIPPING COSTS

select country United States
State: puerto rico
zipcde 00641

Available Shipping Methods | Rates

shows NO quotes at all.  Works only when select country is puerto rico

Thank you!

**Comment by lat9** [comment]
Hmm, running USPS K11j on zc200:

![image](https://github.com/lat9/usps/assets/2685585/20893c14-227c-4708-8ade-a19c32d7cbc1)

**Comment by jjone** [comment]
im running 1.5.8a. maybe thats is why, Thank you lat9!

**Comment by lat9** [comment]
I'll give it a try on 1.5.8a and let you know.  Thanks for the additional information.

**Comment by jjone** [comment]
Thank you so much lat9 !

**Comment by lat9** [comment]
1.5.8a, still quotes received.  What Domestic Rates do you have enabled?

**Comment by jjone** [comment]
![2024-04-12_17-16-05](https://github.com/lat9/usps/assets/8607130/4a41edce-236e-4f78-ad6b-8ad628af4d5c)

i have these 2 rates turned on,

Domestic Rates: Priority,   International Rates: Priority Intl

nothing else.

Thank you lat9 !

**Comment by lat9** [comment]
![image](https://github.com/lat9/usps/assets/2685585/97e6fa8a-9950-44a3-b311-b85c5b80a377)

What's the weight on the package?

**Comment by jjone** [comment]
I tried a few different weights,
Weight: 3.3 lbs
Weight: 37 lbs

**Comment by jjone** [comment]
works now, 

i deleted the PR from zone and added it back.

Thank you so much lat9.!

**Comment by jjone** [comment]
USPS module works great , its the ZC 158a zone problem.
