### ISSUE TITLE
small tweaks to Wiki doc

### ISSUE THREAD

**Issue by scottcwilson** [lat9/usps#46]
Github doesn't let me open a PR, but here are the changes I would suggest to this (excellent!) doc page just to prevent confusion. 
[Initial-Install:-Getting-USPS-Credentials.md](https://github.com/lat9/usps/files/14962390/Initial-Install.-Getting-USPS-Credentials.md)

**Comment by lat9** [comment]
I don't quite get the changes.  I see the addition of the "if you just forgot your password, go here", but after retrieving that forgotten password, do users need to re-request access to those shipping APIs?

**Comment by scottcwilson** [comment]
UPDATED - Suggested changes are:
- Number the 3 steps.
- Link to the forgotten password page 
- Indicate ALL STEPS can be skipped if a userid and pass are known

**Comment by lat9** [comment]
Same API.  If the USERID is already valid for the account, resetting the PASSWORD _shouldn't_ have an effect.

**Comment by scottcwilson** [comment]
It has been so long since I did this I thought it was new.  LOL.  
ok updated suggestions.

**Comment by lat9** [comment]
Wiki updated: https://github.com/lat9/usps/wiki/Initial-Install:-Getting-USPS-Credentials

**Comment by scottcwilson** [comment]
Beautiful!  Even I won't get confused now (hopefully!)
